---
- hosts: localhost
  become: true
  become_method: sudo
  vars:
    wsl_distro: Ubuntu-22.04
  roles:
    - python
    - nodejs
    - global-npm
    - aws-cli-v2
    - aws-sam-cli
    - azure-cli
    - docker
