---
- hosts: localhost
  become: true
  become_method: sudo
  vars:
    wsl_distro: Ubuntu-22.04
  roles:
    - global-apt
    - wsl-config
    - python
    - nodejs
    - global-npm
    - aws-cli-v2
    - azure-cli
    - docker
    - kubectl
    - helm
    - terraform
