---
- name: Copy global WSL config into user profile
  copy:
    src: .wslconfig
    dest: /mnt/c/Users/Finlay/.wslconfig

- name: Copy distro WSL config
  copy:
    src: wsl.conf
    dest: /etc/wsl.conf
