---
- name: Setup Node.js LTS
  shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

- name: Install Node.js LTS
  apt:
    pkg:
      - nodejs
    state: latest
    update_cache: true
