---
- name: Add deadsnakes repository
  apt_repository:
    repo: "ppa:deadsnakes/ppa"

# TODO: Remove once fixed upstream -- see https://github.com/pre-commit/pre-commit/issues/2299
- name: Add deadsnakes jammy repository for venv patch
  apt_repository:
    repo: "ppa:deadsnakes/python3.10-jammy"

- name: Install Python packages
  apt:
    pkg:
      - python3.8
      - python3.8-venv
      - python3.8-distutils
      - python3.9
      - python3.9-venv
      - python3.9-distutils
      - python3.10
      - python3.10-venv
      - python3.10-distutils
      - python3.11
      - python3.11-venv
    state: latest
    update_cache: true
