---
- name: Add HashiCorp GPG key
  shell: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg]  https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: /etc/apt/sources.list.d/hashicorp.list

- name: Install terraform package
  apt:
    pkg:
      - terraform
    state: latest
    update_cache: true
