---
- name: Add Docker GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: /etc/apt/sources.list.d/docker.list

- name: Install Docker packages
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Add user to Docker group
  user:
    name: finlay
    groups: docker

- name: Configure legacy iptables
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Add Docker startup in .bashrc
  blockinfile:
    dest: "/home/finlay/.bashrc"
    block: |
     DOCKER_DISTRO="{{ wsl_distro }}"
     DOCKER_LOG_DIR=$HOME/docker_logs
     mkdir -pm o=,ug=rwx "$DOCKER_LOG_DIR"
     /mnt/c/Windows/System32/wsl.exe -d $DOCKER_DISTRO sh -c "nohup sudo -b dockerd < /dev/null > $DOCKER_LOG_DIR/dockerd.log 2>&1"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - docker"

- name: Grant passwordless access to dockerd
  community.general.sudoers:
    name: dockerd-access
    state: present
    group: docker
    nopassword: true
    commands: /usr/bin/dockerd
